import math

def soma(x, y):
    return x + y

def subtracao(x, y):
    return x - y

def multiplicacao(x, y):
    return x * y

def divisao(x, y):
    if y == 0:
        return "Erro: Divisão por zero!"
    else:
        return x / y

def potencia(x, y):
    return x ** y

def raiz_quadrada(x):
    if x < 0:
        return "Erro: Não é possível calcular a raiz quadrada de um número negativo!"
    else:
        return math.sqrt(x)

def calculadora():
    print("Escolha a operação:")
    print("1. Soma")
    print("2. Subtração")
    print("3. Multiplicação")
    print("4. Divisão")
    print("5. Potência")
    print("6. Raiz Quadrada")

    escolha = input("Digite sua escolha (1/2/3/4/5/6): ")

    if escolha in ('1', '2', '3', '4', '5', '6'):
        num1 = float(input("Digite o primeiro número: "))
        
        if escolha != '6':
            num2 = float(input("Digite o segundo número: "))
        
        if escolha == '1':
            print("Resultado:", soma(num1, num2))
        elif escolha == '2':
            print("Resultado:", subtracao(num1, num2))
        elif escolha == '3':
            print("Resultado:", multiplicacao(num1, num2))
        elif escolha == '4':
            print("Resultado:", divisao(num1, num2))
        elif escolha == '5':
            print("Resultado:", potencia(num1, num2))
        elif escolha == '6':
            print("Resultado:", raiz_quadrada(num1))
    else:
        print("Escolha inválida!")

calculadora()

